### ISSUE TITLE
Some sample bootstrapping code would be helpful

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [aiven/go-client-codegen#34]
## What can we help you with?

I just want to bootstrap my client and make a request to list project details.

I have exported the `AIVEN_TOKEN` as environment variable so the following code works as expected

```go

const userAgent = "just-me"
 
aivenClient, err := aiven.NewClient(aiven.DebugOpt(true), aiven.UserAgentOpt(userAgent))
	if err != nil {
		log.Fatal(err)
	}
	aivenProjectsListOut, err := aivenClient.ProjectList(ctx)
	if err != nil {
		log.Fatal(err)
	}
```

Now I want to list projects' details.

From what I understand, I must create a new (`project`) `Handler` via [this](https://github.com/aiven/go-client-codegen/blob/main/handler/project/project.go#L114) function.

I was not able to find a way to create and/or initialize a `doer` (given that in the `*client` returned the field is unexported).

## Where would you expect to find this information?

Either in `README.md` or within an `examples` folder.

**Comment by Serpentiel** [comment]
Hey, @pantelis-karamolegkos! 👋

Thank you for bringing this up!

I do agree that some additional examples could benefit the project and expand its influence to other developers that might be interested in using it—I will introduce this topic to the relevant stakeholders.

For now, I can recommend taking a look at the following resources which are already available:

- https://pkg.go.dev/github.com/aiven/go-client-codegen, explore this page, there are some useful things
  - Specifically, [this page](https://pkg.go.dev/github.com/aiven/go-client-codegen/handler@v0.2.0) has some documentation on the available handlers
- Check https://github.com/aiven/aiven-operator/pull/629 out to get some idea on the usage of the code generated client

<br>

> From what I understand, I must create a new (project) Handler via [this](https://github.com/aiven/go-client-codegen/blob/main/handler/project/project.go#L114) function.

No, this isn't needed. You can simply call the relevant method directly via the `aivenClient` that you have instantiated. Here's an example to retrieve the information on a specific project:

```go
const userAgent = "just-me"

aivenClient, err := aiven.NewClient(aiven.DebugOpt(true), aiven.UserAgentOpt(userAgent))
if err != nil {
	log.Fatal(err)
}

aivenProjectGetOut, err := aivenClient.ProjectGet(ctx, "some-project-name")
if err != nil {
	log.Fatal(err)
}

log.Println(fmt.Sprintf("Organization ID: %s", aivenProjectGetOut.OrganizationId))
```

<br>

I hope my answer provides you with the information that you were looking for 🙂.

I will not be closing the issue and will update you once I have more information to share in regards to adding some examples to the project.

**Comment by pantelis-karamolegkos** [comment]
Thanks @Serpentiel 💪🏻 
From my side I am good to go for closing this but overall yes, I agree it would be better if the project's docs/examples get enriched.

**Comment by Serpentiel** [comment]
Hey again, @pantelis-karamolegkos! 👋

That's great to hear. I've just received some information from the relevant stakeholders in regards to expanding the Go client further as a product.

We will be working on more public documentation in the near future, including examples.

Thank you once again for your input, I will close the issue once we have some examples in place 🙌.

**Comment by byashimov** [comment]
It looks like the README now has the correct instructions :)

**Comment by Serpentiel** [comment]
> It looks like the README now has the correct instructions :)

This issue was mostly dedicated to adding examples and usage docs for the Go client. The amount of docs in the README.md still isn't sufficient, IMO. But it's up to you to decide it now 🙂
